image: docker:latest

stages:
  - build

build-image:
  stage: build
  script:
    #- docker build -t thomasoss/testrepo:latest -f Dockerfile .
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile -t thomasoss/testrepo:latest .
  #when: manual

  only:
    - master

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD

default:
  tags:
    - runner-l