image: docker:latest

stages:
  - build
  - push

build-image:
  stage: build
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile -t thomasoss/testrepo:latest .
  #when: manual

push-image:
  stage: push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push thomasoss/testrepo:latest
  dependencies:
    - build-image

  only:
    - master

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD

default:
  tags:
    - runner-l