image: docker:latest

stages:
  - build
  - deploy

build-image:
  stage: build
  script:
    #- docker build -t thomasoss/testrepo:latest -f Dockerfile .
    #- dnf install -y qemu-user-static binfmt-support
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --name builder-user --use
    - docker buildx inspect --bootstrap
    - echo "$DOCKER_PASSWORD" | docker login registry.cpe.granux.fr -u "$DOCKER_USERNAME" --password-stdin
    - docker buildx build --push --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile -t registry.cpe.granux.fr/hllmp/konzik-front:latest .
  when: manual

deploy-image:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$OVH" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh debian@ssh debian@162.19.68.172

  only:
    - master

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD

default:
  tags:
    - runner-l